name: dagger
on:
  push:
    branches:
      - "**"

jobs:
  staticAnalysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Static Analysis Checks
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: "static-analysis --source=."
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: 0.16.3