name: dagger
on:
  push:
    branches:
      - "**"

jobs:
  build-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Environment
        uses: dagger/dagger-for-github@8.0.0
        with:
          args: call
          dagger-flags: "build-env --source=."
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: 0.16.3
          